/**
 * Taza Route — Recycling points dataset (demo / hackathon MVP).
 * Locations reference real Almaty-area organizations; coordinates are approximate for map display.
 * @see https://kazakhstankagazy.com — Kazakhstan Kagazy / Kagazy Recycling network
 */

const RECYCLING_POINTS = [
  {
    id: 'kagazy-plant',
    lat: 43.3178,
    lng: 76.8241,
    categories: ['paper', 'plastic', 'glass'],
    nameKk: 'Kagazy Recycling өңдеу орталығы',
    nameRu: 'Перерабатывающий центр Kagazy Recycling',
    addressKk: 'Абай кенті, Алматы облысы (негізгі зауыт аймағы)',
    addressRu: 'пос. Абай, Алматинская область (зона основного завода)',
    hoursKk: 'Дс–Жм 08:00–17:00',
    hoursRu: 'Пн–Пт 08:00–17:00',
    materialsKk: [
      'Макулатура (газет, кітап, қорап)',
      'Пластик құты және Tetra Pak',
      'Шыны бөтелке (тазаланған)',
    ],
    materialsRu: [
      'Макулатура (газеты, книги, картон)',
      'ПЭТ-бутылки и Tetra Pak',
      'Стеклянные бутылки (очищенные)',
    ],
  },
  {
    id: 'kagazy-city-point',
    lat: 43.2529,
    lng: 76.9136,
    categories: ['paper', 'plastic'],
    nameKk: 'Қазақстан Қағазы — қабылдау пункті',
    nameRu: 'Казахстан Кагазы — пункт приёма',
    addressKk: 'Алматы, Жолдасбеков пен Меңдықұлов көшелерінің қиылысы маңы',
    addressRu: 'г. Алматы, район пересечения ул. Жолдасбекова и Мендыкулова',
    hoursKk: 'Жұмыс уақыты: ұйымнан нақтылаңыз',
    hoursRu: 'График: уточняйте у организации',
    materialsKk: ['Макулатура', 'Пластик құты', 'Сусын картондары'],
    materialsRu: ['Макулатура', 'Пластиковые бутылки', 'Тетрапак'],
  },
  {
    id: 'eco-gorod',
    lat: 43.2387,
    lng: 76.8894,
    categories: ['plastic', 'glass', 'paper'],
    nameKk: 'Эко Город — қайта өңдеу компаниясы',
    nameRu: 'Эко Город — компания по переработке',
    addressKk: 'Алматы, Абай даңғылы бойындағы қабылдау пункті (демо орналасу)',
    addressRu: 'г. Алматы, пункт приёма вдоль проспекта Абая (демо-позиция на карте)',
    hoursKk: 'Дс–Сб 09:00–18:00',
    hoursRu: 'Пн–Сб 09:00–18:00',
    materialsKk: ['ПЭТ 1–2 тип', 'Қағаз', 'Шыны'],
    materialsRu: ['ПЭТ типы 1–2', 'Бумага', 'Стекло'],
  },
  {
    id: 'green-smart',
    lat: 43.2214,
    lng: 76.8512,
    categories: ['electronics', 'hazardous'],
    nameKk: 'Green Smart — электрондық қалдық',
    nameRu: 'Green Smart — утилизация электроники',
    addressKk: 'Алматы, орталық аудан, Төле би көшесі маңы',
    addressRu: 'г. Алматы, центральный район, район ул. Толе би',
    hoursKk: 'Дс–Жм 10:00–19:00',
    hoursRu: 'Пн–Пт 10:00–19:00',
    materialsKk: [
      'Телефон, ноутбук, планшет',
      'Батареялар мен аккумуляторлар',
      'Кіші пластик электроника',
    ],
    materialsRu: [
      'Телефоны, ноутбуки, планшеты',
      'Батарейки и аккумуляторы',
      'Мелкая электроника',
    ],
  },
  {
    id: 'battery-box',
    lat: 43.2561,
    lng: 76.9288,
    categories: ['hazardous'],
    nameKk: 'Түсті металл және батарея жинайтын орталық',
    nameRu: 'Пункт приёма батареек и цветмета',
    addressKk: 'Алматы, Әуезов ауданы, сауда орталығы маңы',
    addressRu: 'г. Алматы, Ауэзовский р-н, у торгового центра (ориентир)',
    hoursKk: 'Күнделікті 10:00–20:00',
    hoursRu: 'Ежедневно 10:00–20:00',
    materialsKk: ['Сарқылған батареялар', 'Қауіпті тұрмыстық тұздықтар (шектеулі)'],
    materialsRu: ['Отработанные батарейки', 'Опасные бытовые отходы (ограниченно)'],
  },
  {
    id: 'glass-hub',
    lat: 43.2042,
    lng: 76.8705,
    categories: ['glass'],
    nameKk: 'Шыны қайта өңдеу хабы',
    nameRu: 'Хаб переработки стекла',
    addressKk: 'Алматы, оңтүстік-industrial аудан (демо координата)',
    addressRu: 'г. Алматы, юго-промышленная зона (демо-координата)',
    hoursKk: 'Дс–Жм 08:00–16:00',
    hoursRu: 'Пн–Пт 08:00–16:00',
    materialsKk: ['Таза шыны бөтелке', 'Терезе шынысы (қорғасынсыз)'],
    materialsRu: ['Чистые стеклотара', 'Оконное стекло (без свинца)'],
  },
  {
    id: 'paper-union',
    lat: 43.2713,
    lng: 76.9458,
    categories: ['paper'],
    nameKk: 'Қағаз вторсырье қабылдау',
    nameRu: 'Приём вторсырья — бумага',
    addressKk: 'Алматы, қатты тұрмыстық қалдық алаңы маңы (демо)',
    addressRu: 'г. Алматы, район полигона ТКО (демо-метка)',
    hoursKk: 'Дс–Сб 07:00–15:00',
    hoursRu: 'Пн–Сб 07:00–15:00',
    materialsKk: ['Картон', 'Газет', 'Кеңселік қағаз'],
    materialsRu: ['Картон', 'Газеты', 'Офисная бумага'],
  },

  // --- Freedom Recycling (Eco Network) — Almaty fendomats / eco-boxes (plastic + paper) ---
  // Sources: 2GIS Freedom branches (coordinates from the “Проехать” link).
  // Note: Many fendomats accept PET bottles primarily; we tag as plastic+paper for hackathon MVP filtering.
  {
    id: 'freedom-markova-44',
    brand: 'freedom',
    lat: 43.228482,
    lng: 76.933036,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — Марков көш., 44',
    nameRu: 'Freedom Recycling Box — ул. Маркова, 44',
    addressKk: 'Алматы, Марков көшесі, 44 (Eco Network фандомат)',
    addressRu: 'Алматы, улица Маркова, 44 (фандомат Eco Network)',
    hoursKk: 'Бүгін: 09:00–18:00',
    hoursRu: 'Сегодня: 09:00–18:00',
    materialsKk: ['ПЭТ бөтелкелер', 'Қағаз (MVP демо)'],
    materialsRu: ['ПЭТ-бутылки', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-terracotta-abai-164-6k6',
    brand: 'freedom',
    lat: 43.236212,
    lng: 76.879007,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — ЖК Terracotta',
    nameRu: 'Freedom Recycling Box — ЖК Terracotta',
    addressKk: 'Алматы, Абай даңғ., 164/6 к6 (фандомат)',
    addressRu: 'Алматы, проспект Абая, 164/6 к6 (фандомат)',
    hoursKk: 'Күн сайын: 10:00–19:00',
    hoursRu: 'Ежедневно: 10:00–19:00',
    materialsKk: ['Пластик бөтелке', 'Қағаз (MVP демо)'],
    materialsRu: ['Пластиковые бутылки', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-almau-rozybakieva-227',
    brand: 'freedom',
    lat: 43.206237,
    lng: 76.893439,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — AlmaU',
    nameRu: 'Freedom Recycling Box — AlmaU',
    addressKk: 'Алматы, Розыбакиев көш., 227 (AlmaU жанында)',
    addressRu: 'Алматы, улица Розыбакиева, 227 (рядом с AlmaU)',
    hoursKk: 'Бүгін: 09:00–18:00',
    hoursRu: 'Сегодня: 09:00–18:00',
    materialsKk: ['ПЭТ', 'Қағаз (MVP демо)'],
    materialsRu: ['ПЭТ', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-nurikon-auezova-175-1',
    brand: 'freedom',
    lat: 43.227485,
    lng: 76.905245,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — БЦ NURIKON',
    nameRu: 'Freedom Recycling Box — БЦ NURIKON',
    addressKk: 'Алматы, Әуезов көш., 175/1 (БЦ NURIKON)',
    addressRu: 'Алматы, улица Ауэзова, 175/1 (БЦ NURIKON)',
    hoursKk: 'Бүгін: 07:00–20:00',
    hoursRu: 'Сегодня: 07:00–20:00',
    materialsKk: ['Пластик', 'Қағаз (MVP демо)'],
    materialsRu: ['Пластик', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-cska-abai-159',
    brand: 'freedom',
    lat: 43.239124,
    lng: 76.88906,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — СТК ЦСКА',
    nameRu: 'Freedom Recycling Box — СТК ЦСКА',
    addressKk: 'Алматы, Абай даңғ., 159 (СТК ЦСКА)',
    addressRu: 'Алматы, проспект Абая, 159 (СТК ЦСКА)',
    hoursKk: 'Күн сайын: 07:00–22:00',
    hoursRu: 'Ежедневно: 07:00–22:00',
    materialsKk: ['ПЭТ бөтелке', 'Қағаз (MVP демо)'],
    materialsRu: ['ПЭТ-бутылки', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-narhoz-zhandosova-55',
    brand: 'freedom',
    lat: 43.214629,
    lng: 76.871222,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — Нархоз',
    nameRu: 'Freedom Recycling Box — Нархоз',
    addressKk: 'Алматы, Ораза Жандосов көш., 55 (Нархоз)',
    addressRu: 'Алматы, улица Ораза Жандосова, 55 (Нархоз)',
    hoursKk: 'Күн сайын: 10:00–22:00',
    hoursRu: 'Ежедневно: 10:00–22:00',
    materialsKk: ['Пластик бөтелке', 'Қағаз (MVP демо)'],
    materialsRu: ['Пластиковые бутылки', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-dulati-1-3',
    brand: 'freedom',
    lat: 43.189798,
    lng: 76.884798,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — Дулати даңғ., 1/3',
    nameRu: 'Freedom Recycling Box — пр-т Дулати, 1/3',
    addressKk: 'Алматы, Дулати даңғылы, 1/3 (Fresh Up маңы)',
    addressRu: 'Алматы, проспект Дулати, 1/3 (около Fresh Up)',
    hoursKk: 'Тәулік бойы',
    hoursRu: 'Круглосуточно',
    materialsKk: ['ПЭТ', 'Қағаз (MVP демо)'],
    materialsRu: ['ПЭТ', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-bayzak-abai-52v',
    brand: 'freedom',
    lat: 43.238497,
    lng: 76.914105,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — БЦ Bayzak',
    nameRu: 'Freedom Recycling Box — БЦ Bayzak',
    addressKk: 'Алматы, Абай даңғ., 52в (БЦ Bayzak)',
    addressRu: 'Алматы, проспект Абая, 52в (БЦ Bayzak)',
    hoursKk: 'Бүгін: 08:00–21:00',
    hoursRu: 'Сегодня: 08:00–21:00',
    materialsKk: ['Пластик', 'Қағаз (MVP демо)'],
    materialsRu: ['Пластик', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-megapolis-mamyr-1-26-1b2',
    brand: 'freedom',
    lat: 43.21159,
    lng: 76.84834,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — ЖК Megapolis',
    nameRu: 'Freedom Recycling Box — ЖК Megapolis',
    addressKk: 'Алматы, Мамыр-1 мкр., 26/1 (2-блок)',
    addressRu: 'Алматы, мкр. Мамыр-1, 26/1 (блок 2)',
    hoursKk: 'Күн сайын: 10:00–20:00',
    hoursRu: 'Ежедневно: 10:00–20:00',
    materialsKk: ['ПЭТ бөтелке', 'Қағаз (MVP демо)'],
    materialsRu: ['ПЭТ-бутылки', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-esentai-alfarabi-77-7',
    brand: 'freedom',
    lat: 43.219129,
    lng: 76.9292,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — Esentai Tower',
    nameRu: 'Freedom Recycling Box — Esentai Tower',
    addressKk: 'Алматы, Әл-Фараби даңғ., 77/7 (Esentai Tower)',
    addressRu: 'Алматы, проспект Аль-Фараби, 77/7 (Esentai Tower)',
    hoursKk: 'Бүгін: 08:00–19:00',
    hoursRu: 'Сегодня: 08:00–19:00',
    materialsKk: ['Пластик', 'Қағаз (MVP демо)'],
    materialsRu: ['Пластик', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-fortis-khodzhanova-2-2',
    brand: 'freedom',
    lat: 43.210343,
    lng: 76.908023,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — БЦ Fortis',
    nameRu: 'Freedom Recycling Box — БЦ Fortis',
    addressKk: 'Алматы, Ходжанов көш., 2/2 (БЦ Fortis)',
    addressRu: 'Алматы, улица Ходжанова, 2/2 (БЦ Fortis)',
    hoursKk: 'Бүгін: 09:00–18:00',
    hoursRu: 'Сегодня: 09:00–18:00',
    materialsKk: ['ПЭТ', 'Қағаз (MVP демо)'],
    materialsRu: ['ПЭТ', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-shevchenko-97',
    brand: 'freedom',
    lat: 43.245613,
    lng: 76.929772,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — Шевченко көш., 97',
    nameRu: 'Freedom Recycling Box — ул. Шевченко, 97',
    addressKk: 'Алматы, Шевченко көшесі, 97 (АЛТ жанында)',
    addressRu: 'Алматы, улица Шевченко, 97 (около АЛТ)',
    hoursKk: 'Күн сайын: 08:30–19:30',
    hoursRu: 'Ежедневно: 08:30–19:30',
    materialsKk: ['Пластик бөтелке', 'Қағаз (MVP демо)'],
    materialsRu: ['Пластиковые бутылки', 'Бумага (MVP демо)'],
  },
  {
    id: 'freedom-alfarabi-71-21',
    brand: 'freedom',
    lat: 43.21962,
    lng: 76.921557,
    categories: ['plastic', 'paper'],
    nameKk: 'Freedom Recycling Box — Әл-Фараби даңғ., 71/21',
    nameRu: 'Freedom Recycling Box — пр-т Аль-Фараби, 71/21',
    addressKk: 'Алматы, Әл-Фараби даңғылы, 71/21 (фандомат)',
    addressRu: 'Алматы, проспект Аль-Фараби, 71/21 (фандомат)',
    hoursKk: 'Жұмыс уақыты: нақтылаңыз',
    hoursRu: 'График: уточняйте',
    materialsKk: ['ПЭТ', 'Қағаз (MVP демо)'],
    materialsRu: ['ПЭТ', 'Бумага (MVP демо)'],
  },
];

/** Category metadata for filters and marker styling */
const CATEGORY_META = {
  // `faIcon` is used for premium HTML markers + filter chips.
  plastic: { color: '#0ea5e9', faIcon: 'fa-solid fa-bottle-water', icon: '♻️' },
  paper: { color: '#22c55e', faIcon: 'fa-regular fa-file-lines', icon: '📄' },
  glass: { color: '#a855f7', faIcon: 'fa-solid fa-wine-glass', icon: '🍾' },
  electronics: { color: '#f59e0b', faIcon: 'fa-solid fa-microchip', icon: '💻' },
  hazardous: { color: '#ef4444', faIcon: 'fa-solid fa-battery-three-quarters', icon: '🔋' },
};
